declare const styles: {
  page: string;
  pageHeader: string;
  title: string;
  subtitle: string;
  summaryGrid: string;
  summaryCard: string;
  panel: string;
  editPanel: string;
  toolbar: string;
  controlGroup: string;
  controlGroupInline: string;
  refreshButton: string;
  primaryButton: string;
  secondaryButton: string;
  linkButton: string;
  clearButton: string;
  dangerButton: string;
  feedback: string;
  error: string;
  tableWrapper: string;
  table: string;
  statusBadge: string;
  actionRow: string;
  titleLinkButton: string;
  editModalContainer: string;
  editModalHeader: string;
  editModalTitle: string;
  editDesc: string;
  lockedHint: string;
  editGrid: string;
  approverPanel: string;
  userList: string;
  userItem: string;
  selectedApprover: string;
  editActions: string;
};

export default styles;
